# project_init.bash
# example> vitis_startup
# example> source project_init.bash

echo
echo ==================================================
echo INIT PROJECT VARIABLES
#export PROJECT_BOARD_NAME=zybo_z7_20
#export PROJECT_VITIS_VERSION=2022_2
#export PROJECT_NAME=${PROJECT_BOARD_NAME}_base_$PROJECT_VITIS_VERSION
export PROJECT_DIR=$PWD
export PROJECT_NAME=$(basename $PROJECT_DIR)
export PROJECT_HARDWARE_DIR=$PROJECT_DIR/hardware
export PROJECT_VIVADO_NAME=${PROJECT_NAME}-vivado
export PROJECT_VIVADO_DIR=$PROJECT_HARDWARE_DIR/${PROJECT_NAME}-vivado
export PROJECT_XSA_FILE=$PROJECT_VIVADO_DIR/${PROJECT_NAME}_wrapper.xsa
export PROJECT_IMPL_DIR=$PROJECT_VIVADO_DIR/$PROJECT_VIVADO_NAME.runs/impl_1
export PROJECT_BIT_FILE=$PROJECT_IMPL_DIR/${PROJECT_NAME}_wrapper.bit
export PROJECT_SOFTWARE_DIR=$PROJECT_DIR/software
export PROJECT_LINUX_FILES_DIR=$PROJECT_SOFTWARE_DIR/linux_files
export PROJECT_BOOT_DIR=$PROJECT_LINUX_FILES_DIR/boot
export PROJECT_IMAGE_DIR=$PROJECT_LINUX_FILES_DIR/image
export PROJECT_PETALINUX_NAME=${PROJECT_NAME}-petalinux
export PROJECT_PETALINUX_DIR=$PROJECT_SOFTWARE_DIR/$PROJECT_PETALINUX_NAME
export PROJECT_BUILD_DIR=/tftpboot
export PROJECT_UDEMY_RESOURCES_DIR=~/Downloads/udemy
export PROJECT_PLATFORM_DIR=$PROJECT_DIR/platform
env |grep 'PROJECT_.*='

