# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_z7_20_base_2022_2/zybo_z7_20_base_2022_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2022_2 || ORIG_REF_NAME==zybo_z7_20_base_2022_2} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2022_2/ip/zybo_z7_20_base_2022_2_processing_system7_0_0/zybo_z7_20_base_2022_2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2022_2_processing_system7_0_0 || ORIG_REF_NAME==zybo_z7_20_base_2022_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2022_2/ip/zybo_z7_20_base_2022_2_clk_wiz_0_0/zybo_z7_20_base_2022_2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2022_2_clk_wiz_0_0 || ORIG_REF_NAME==zybo_z7_20_base_2022_2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2022_2/ip/zybo_z7_20_base_2022_2_proc_sys_reset_0_0/zybo_z7_20_base_2022_2_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2022_2_proc_sys_reset_0_0 || ORIG_REF_NAME==zybo_z7_20_base_2022_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2022_2/ip/zybo_z7_20_base_2022_2_proc_sys_reset_0_1/zybo_z7_20_base_2022_2_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2022_2_proc_sys_reset_0_1 || ORIG_REF_NAME==zybo_z7_20_base_2022_2_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2022_2/ip/zybo_z7_20_base_2022_2_proc_sys_reset_0_2/zybo_z7_20_base_2022_2_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2022_2_proc_sys_reset_0_2 || ORIG_REF_NAME==zybo_z7_20_base_2022_2_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2022_2/ip/zybo_z7_20_base_2022_2_xlconcat_0_0/zybo_z7_20_base_2022_2_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2022_2_xlconcat_0_0 || ORIG_REF_NAME==zybo_z7_20_base_2022_2_xlconcat_0_0} -quiet] -quiet

# XDC: /home/jwrr/vitis/fpga-xilinx-vitis-2022.2-zybo_z7_20/zybo_z7_20/hardware/zybo_z7_20_2022_2-vivado/zybo_z7_20_2022_2-vivado.gen/sources_1/bd/zybo_z7_20_base_2022_2/zybo_z7_20_base_2022_2_ooc.xdc
